using System.Text;
using System.Text.RegularExpressions;

namespace DatabaseManager.Core.Services;

/// <summary>
/// Splits a script on "GO" batch-separator lines (the SSMS/sqlcmd convention, not real T-SQL -
/// SqlCommand chokes on a literal "GO"). Scripts generated by SSMS ("Script Stored Procedure as
/// CREATE") routinely start with USE/SET .../GO boilerplate before the statement that actually
/// matters, so a single-batch assumption breaks both execution and CREATE/ALTER-routine detection.
/// </summary>
public static class QueryBatchSplitter
{
    private static readonly Regex GoSeparatorLine = new(
        @"^\s*GO\s*(\d+)?\s*$",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    public static IReadOnlyList<string> Split(string sql)
    {
        if (string.IsNullOrWhiteSpace(sql))
        {
            return Array.Empty<string>();
        }

        var batches = new List<string>();
        var currentBatch = new StringBuilder();

        foreach (var line in sql.Split('\n'))
        {
            if (GoSeparatorLine.IsMatch(line.TrimEnd('\r')))
            {
                AppendBatchIfNotEmpty(batches, currentBatch);
                currentBatch.Clear();
                continue;
            }

            currentBatch.Append(line).Append('\n');
        }

        AppendBatchIfNotEmpty(batches, currentBatch);

        return batches.Count == 0 ? new List<string> { sql } : batches;
    }

    private static void AppendBatchIfNotEmpty(List<string> batches, StringBuilder currentBatch)
    {
        var text = currentBatch.ToString().Trim();
        if (text.Length > 0)
        {
            batches.Add(text);
        }
    }
}
